### ISSUE TITLE
timeLine 

### ISSUE THREAD

**Issue by Belgianwafflecorp** [vives-project-xp/BachelorproefKiosk#129]
maken van een timeline die toont wat we wanneer gedaan hebben en wat nog moet gebeuren.

**Comment by SampersS** [comment]
Dit is de tijdlijn van mij (ongeveer):

database + backend: week 1 - 2
javascript voor pagina invulling: week 2 - 4
hardware voor knoppen en joystick: week 3 - 5
architectuur juist krijgen: week 2 - 5
website finaliseren + admin pagina: week 4 - 6
dockerizeren website: week 4 - 6
kennis making met wordpress: week 7 - 8
website in wordpress zetten: week 8 - 10
dockeriseren wordpress: week 8 - 9
sync script: week 9
