### ISSUE TITLE
verfijning van frontend

### ISSUE THREAD

**Issue by SampersS** [vives-project-xp/BachelorproefKiosk#14]
deze dingen moeten veranderen aan de project pagina:
-hashtags worden niet als array opgeslagen in de database maar als een string, dus de li items moeten weg
-er is nog een img object nodig voor de 2de foto
-als je op het linkidin logo klikt wordt je niet doorverwezen naar linkidin, dit moet nog gefixt worden, ik heb gewoon de href van het element van de klasse Linkedin ingevult, als de link ergens anders moet komen mag je de js zelf aanpassen of aan mij vragen.
Er is een html document terug te vinden van hoe de pagina er ingevult uitzag (wel zonder css) in de map website.

**Comment by Kenrie19** [comment]
"-als je op het linkidin logo klikt wordt je niet doorverwezen naar linkidin, dit moet nog gefixt worden, ik heb gewoon de href van het element van de klasse Linkedin ingevult, als de link ergens anders moet komen mag je de js zelf aanpassen of aan mij vragen."

Dit zullen we anders oplossen door middel van een Qr code.
