### ISSUE TITLE
Admin Page maken

### ISSUE THREAD

**Issue by Kenrie19** [vives-project-xp/BachelorproefKiosk#15]
Alle invulvelden voor de fiches erin zetten.

**Comment by SampersS** [comment]
![IMG_20240226_092316](https://github.com/vives-project-xp/BachelorproefKiosk/assets/74018386/ffe82d06-b673-4cf0-8dc1-bb966ddd4667)

**Comment by SampersS** [comment]
is al beschikbaar maar we gaan toch gebruik maken van wordpress dus we hadden dit niet eens nodig.
