### ISSUE TITLE
Opzoekwerk voor Qr code

### ISSUE THREAD

**Issue by Kenrie19** [vives-project-xp/BachelorproefKiosk#20]

**Comment by Kenrie19** [comment]
/* Load the library */
    <script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
    
    /* Basic and simple one */
    <div id="qrcode"></div>
    <script type="text/javascript">
    new QRCode(document.getElementById("qrcode"), "https://webisora.com");
    </script>

**Comment by Belgianwafflecorp** [comment]
Opzoek werk is niet compleet maar de nood aan een QR-code is er niet meer. Er word nu gebruik gemaakt van pdf documenten.
